<?php

namespace CL\TicketingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
  public function findNbTicketsOnDate(\DateTime $date)
  {
    $qb = $this->createQueryBuilder('p');

    $qb->select('sum(p.ticketNb)')
        // ->select('p.ticketNb')
        ->where('p.visitDate = :date')
        ->setParameter('date', $date)
        ;
// dump($date);
// dump($qb
// ->getQuery()
// ->getResult());
// die;
        return $qb
       ->getQuery()
       // ->getResult()
       ->getSingleScalarResult();
     ;
  }
}
