# src/CL/TicketingBundle/Resources/config/services.yml

services:
   # cl_ticketing.example:
   #     class: CL\TicketingBundle\Example
   #     arguments: ["@service_id", "plain_value", "%parameter%"]

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }

   cl_ticketing.manager:
       class: CL\TicketingBundle\Services\TicketingManager
       arguments:
         - "@doctrine.orm.entity_manager"


   cl_ticketing.generateCode:
       class: CL\TicketingBundle\Services\GenerateCodeWithDate
       arguments:
          - "@doctrine.orm.entity_manager"

   cl_ticketing.definePriceByBirthday:
       class: CL\TicketingBundle\Services\PriceByBirthday

   cl_ticketing.defineTotalPrice:
       class: CL\TicketingBundle\Services\AddedPrices

   cl_ticketing.hydrateTicket:
       class: CL\TicketingBundle\Services\HydrateTicket
       arguments:
          - "@session"
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.definePriceByBirthday"
          - "@cl_ticketing.convertDatepickerInDatetime"

   cl_ticketing.hydratePurchase:
       class: CL\TicketingBundle\Services\HydratePurchase
       arguments:
          - "@session"
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.defineTotalPrice"
          - "@cl_ticketing.convertDatepickerInDatetime"

   cl_ticketing.convertDatepickerInDatetime:
       class: CL\TicketingBundle\Services\ConvertDatepickerInDatetime
       arguments:
          - %locale%



   cl_ticketing.validator.noMore:
       class: CL\TicketingBundle\Validator\NoMoreValidator
       arguments:
         - "@doctrine.orm.entity_manager"
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noMore }
