# src/CL/TicketingBundle/Resources/config/services.yml

services:
   # cl_ticketing.example:
   #     class: CL\TicketingBundle\Example
   #     arguments: ["@service_id", "plain_value", "%parameter%"]

   cl_ticketing.generateCode:
       class: CL\TicketingBundle\Services\GenerateCode\GenerateCodeWithDate
