# src/CL/TicketingBundle/Resources/config/services.yml

services:
   # cl_ticketing.example:
   #     class: CL\TicketingBundle\Example
   #     arguments: ["@service_id", "plain_value", "%parameter%"]

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }

   cl_ticketing.manager:
       class: CL\TicketingBundle\Services\TicketingManager
       arguments:
         - "@session"


   cl_ticketing.generateCode:
       class: CL\TicketingBundle\Services\GenerateCodeWithDate

   cl_ticketing.definePriceByBirthday:
       class: CL\TicketingBundle\Services\PriceByBirthday

   cl_ticketing.defineTotalPrice:
       class: CL\TicketingBundle\Services\AddedPrices

   cl_ticketing.hydrateTicket:
       class: CL\TicketingBundle\Services\HydrateTicket
       arguments:
          - "@session"
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.definePriceByBirthday"

   cl_ticketing.hydratePurchase:
       class: CL\TicketingBundle\Services\HydratePurchase
       arguments:
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.defineTotalPrice"
