# src/CL/TicketingBundle/Resources/config/services.yml

parameters:
   ticketing_age_ranges: { "child_age_mini": 4, "child_age_maxi":12, "senior_age_mini": 60 }

   ticketing_closed_days:
       - "01-01"
       - "05-01"
       - "05-08"
       - "07-14"
       - "08-15"
       - "11-01"
       - "11-11"
       - "12-25"

   ticketing_closed_holiday : { "paques_closed": true, "ascension_closed": true, "pentecote_closed":true }

   ticketing_general: { max_tickets_by_day: 1000, half_day_hour: 14, past_day_hour: 16.30 }

   ticket_prices: { normal_price_day: 16, normal_price_half: 9, child_price_day: 8, child_price_half: 5, senior_price_day: 12, senior_price_half: 7, reduced_price_day: 10, reduced_price_half: 6 }


services:

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }

   cl_ticketing.manager:
       class: CL\TicketingBundle\Services\TicketingManager
       arguments:
         - "@doctrine.orm.entity_manager"

   cl_ticketing.generateCode:
       class: CL\TicketingBundle\Services\GenerateCodeWithDate
       arguments:
          - "@doctrine.orm.entity_manager"

   cl_ticketing.definePriceByBirthday:
       class: CL\TicketingBundle\Services\PriceByBirthday
       arguments:
          - '%ticketing_age_ranges%'
          - '%ticket_prices%'

   cl_ticketing.defineTotalPrice:
       class: CL\TicketingBundle\Services\AddedPrices

   cl_ticketing.hydrateTicket:
       class: CL\TicketingBundle\Services\HydrateTicket
       arguments:
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.definePriceByBirthday"
          - "@cl_ticketing.convertDatepickerInDatetime"
          - '%ticket_prices%'

   cl_ticketing.hydratePurchase:
       class: CL\TicketingBundle\Services\HydratePurchase
       arguments:
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.defineTotalPrice"
          - "@cl_ticketing.convertDatepickerInDatetime"

   cl_ticketing.convertDatepickerInDatetime:
       class: CL\TicketingBundle\Services\ConvertDatepickerInDatetime
       arguments:
          - "%locale%"

   cl_ticketing.definePaques:
       class: CL\TicketingBundle\Services\DefinePaques

   cl_ticketing.defineAscension:
       class: CL\TicketingBundle\Services\DefineAscension

   cl_ticketing.definePentecote:
       class: CL\TicketingBundle\Services\DefinePentecote



# Services Validator
# ==============================
   cl_ticketing.validator.entireDay:
       class: CL\TicketingBundle\Validator\EntireDayValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
         - "%ticketing_general%"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_entireDay }

   cl_ticketing.validator.noPastHour:
       class: CL\TicketingBundle\Validator\NoPastHourValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
         - "%ticketing_general%"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noPastHour }

   cl_ticketing.validator.isOpen:
       class: CL\TicketingBundle\Validator\IsOpenValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
         - "@cl_ticketing.definePaques"
         - "@cl_ticketing.defineAscension"
         - "@cl_ticketing.definePentecote"
         - "%ticketing_closed_days%"
         - "%ticketing_closed_holiday%"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_isOpen }

   cl_ticketing.validator.noMore:
       class: CL\TicketingBundle\Validator\NoMoreValidator
       arguments:
         - "@doctrine.orm.entity_manager"
         - "@cl_ticketing.convertDatepickerInDatetime"
         - "%ticketing_general%"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noMore }

   cl_ticketing.validator.noPastDays:
       class: CL\TicketingBundle\Validator\NoPastDaysValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noPastDays }


# Service Email
# ==============================
   cl_ticketing.email.ticketingMailler:
       class: CL\TicketingBundle\Email\TicketingMailler
       arguments:
         - "@mailer"
         - "@templating"

   cl_ticketing.doctrineListener.ticketingCreationListener:
       class: CL\TicketingBundle\DoctrineListener\TicketingCreationListener
       arguments:
         - "@cl_ticketing.email.ticketingMailler"
       tags:
         - { name: doctrine.event_listener, event: postPersist }

   cl_ticketing.email.contactMailler:
       class: CL\TicketingBundle\Email\ContactMailler
       arguments:
         - "@mailer"
         - "@templating"
