# src/CL/TicketingBundle/Resources/config/services.yml

services:

   twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
          - { name: twig.extension }

   cl_ticketing.manager:
       class: CL\TicketingBundle\Services\TicketingManager
       arguments:
         - "@doctrine.orm.entity_manager"

   cl_ticketing.generateCode:
       class: CL\TicketingBundle\Services\GenerateCodeWithDate
       arguments:
          - "@doctrine.orm.entity_manager"

   cl_ticketing.definePriceByBirthday:
       class: CL\TicketingBundle\Services\PriceByBirthday

   cl_ticketing.defineTotalPrice:
       class: CL\TicketingBundle\Services\AddedPrices

   cl_ticketing.hydrateTicket:
       class: CL\TicketingBundle\Services\HydrateTicket
       arguments:
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.definePriceByBirthday"
          - "@cl_ticketing.convertDatepickerInDatetime"

   cl_ticketing.hydratePurchase:
       class: CL\TicketingBundle\Services\HydratePurchase
       arguments:
          - "@cl_ticketing.generateCode"
          - "@cl_ticketing.defineTotalPrice"
          - "@cl_ticketing.convertDatepickerInDatetime"

   cl_ticketing.convertDatepickerInDatetime:
       class: CL\TicketingBundle\Services\ConvertDatepickerInDatetime
       arguments:
          - "%locale%"

   cl_ticketing.definePaques:
       class: CL\TicketingBundle\Services\DefinePaques

   cl_ticketing.defineAscension:
       class: CL\TicketingBundle\Services\DefineAscension

   cl_ticketing.definePentecote:
       class: CL\TicketingBundle\Services\DefinePentecote



# Services Validator
# ==============================
   cl_ticketing.validator.entireDay:
       class: CL\TicketingBundle\Validator\EntireDayValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_entireDay }

   cl_ticketing.validator.noPastHour:
       class: CL\TicketingBundle\Validator\NoPastHourValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noPastHour }

   cl_ticketing.validator.isOpen:
       class: CL\TicketingBundle\Validator\IsOpenValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
         - "@cl_ticketing.definePaques"
         - "@cl_ticketing.defineAscension"
         - "@cl_ticketing.definePentecote"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_isOpen }

   cl_ticketing.validator.noMore:
       class: CL\TicketingBundle\Validator\NoMoreValidator
       arguments:
         - "@doctrine.orm.entity_manager"
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noMore }

   cl_ticketing.validator.noPastDays:
       class: CL\TicketingBundle\Validator\NoPastDaysValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noPastDays }

   cl_ticketing.validator.noTuesday:
       class: CL\TicketingBundle\Validator\NoTuesdayValidator
       arguments:
         - "@cl_ticketing.convertDatepickerInDatetime"
       tags:
         - { name: validator.constraint_validator, alias: ticketing_noTuesday }


# Service Email
# ==============================
   cl_ticketing.email.ticketingMailler:
       class: CL\TicketingBundle\Email\TicketingMailler
       arguments:
         - "@mailer"
         - "@templating"

   cl_ticketing.doctrineListener.ticketingCreationListener:
       class: CL\TicketingBundle\DoctrineListener\TicketingCreationListener
       arguments:
         - "@cl_ticketing.email.ticketingMailler"
       tags:
         - { name: doctrine.event_listener, event: postPersist }

   cl_ticketing.email.contactMailler:
       class: CL\TicketingBundle\Email\ContactMailler
       arguments:
         - "@mailer"
         - "@templating"
